import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "mostafa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h3>
          hello i am forme main page 
        </h3>
        <nav style={{backgroundColor : "aqua" , height : "50px" , width : "600px", display:"flex"}}>
          <Link style={{margin: "5px" , padding : "8px"}} href={"http://localhost:3000/kkhh"}><button>go to kkhh oage</button>
          </Link> 
          <Link style={{margin: "5px" , padding : "8px"}} href={"http://localhost:3000/last"}><button>go to last oage</button>
          </Link> 
          <Link style={{margin: "5px" , padding : "8px"}} href={"neww"}><button>go to neww oage</button>
          </Link> 
          <Link style={{margin: "5px" , padding : "8px"}} href={"/"}><button>go to maine oage</button>
          </Link> 
          <Link style={{margin: "5px" , padding : "8px"}} href={"kkhh/nistedPage"}><button>go to nisted oage</button>
          </Link>
        </nav>
        {children}
        </body>
    </html>
  );
}
